// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLdZHGWyA2tJqazlUKfkgg2TBij4th-2Q',
    appId: '1:624882881876:web:910019e15795c4b52364c1',
    messagingSenderId: '624882881876',
    projectId: 'try-app-48957',
    authDomain: 'try-app-48957.firebaseapp.com',
    storageBucket: 'try-app-48957.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdom2AgzX1iF-F6IY8ZmrFvaKZWrPswyk',
    appId: '1:624882881876:android:50a855639f6538f62364c1',
    messagingSenderId: '624882881876',
    projectId: 'try-app-48957',
    storageBucket: 'try-app-48957.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS-b8srpVfu-yeqG92ANNg_GzGhutK6Zo',
    appId: '1:624882881876:ios:0088fdca99f36f1c2364c1',
    messagingSenderId: '624882881876',
    projectId: 'try-app-48957',
    storageBucket: 'try-app-48957.appspot.com',
    iosBundleId: 'com.example.notely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS-b8srpVfu-yeqG92ANNg_GzGhutK6Zo',
    appId: '1:624882881876:ios:ebfb9f6698aafe632364c1',
    messagingSenderId: '624882881876',
    projectId: 'try-app-48957',
    storageBucket: 'try-app-48957.appspot.com',
    iosBundleId: 'com.example.notely.RunnerTests',
  );
}
